# This is the main configuration for FoxBot. All lines have a short explanation.
# For further info, use the below links.
#
# IRC: http://webchat.seion.us/?channels=foxbot
# Issue Tracker: https://github.com/FoxDev/FoxBot/issues

# Used to identify the bot's owner in CTCP version replies. Has no effect on bot operation.
bot-owner: Jackie
bot:
    # The bot's nick.
    nick: GroestlBot
    # The bot's ident. Will show as botnick!ident@host.com
    ident: GroestlBot
    # The name to show in /whois results.
    realname: GroestlBot
server:
    # The server address.
    address: irc.libera.chat
    # The server port.
    port: 6667
    # Should we use SSL?
    ssl: false
    # Should we accept an invalid SSL certificate?
    accept-invalid-ssl-cert: true
    # A password for connecting to the server, if required.
    password: password
    # List of channels for the bot to join on startup. Channel names must be enclosed in ''.
    # If the channel has a key, place it after a :, for example #foxdev:key
    channels:
     #- '#digitalcoin'
     - '#Groestlcoin'
     #- '#foundationdgc'
voice:
    user:
    - 'ahmed__'
    - 'vashthestampede'
auth:
    # Should we use nickserv?
    use-nickserv: true
    # The bot's nickserv password.
    nickserv-password: thisisthenickservpass
    # Do users have to be authed with nickserv to use bot commands?
    users-must-be-verified: false
    # Should we match users based on hostmasks? This mode is secure enough that you don't need to use "users-must-be-verified".
    match-users-by-hostmask: false
user-punishment:
    # Time in seconds to unban users after a bot ban. Set to 0 to disable.
    unban-timer: 86400
misc:
    # If the bot sees a message beginning with this, it is treated as a command. Can only be one character.
    command-prefix: '!'
    # Should the bot accept invites from users with bot.invite?
    auto-join-on-invite: false
    # Should the bot rejoin a channel after being kicked?
    auto-rejoin-on-kick: true
    # How long the bot will wait after being kicked to rejoin a channel.
    auto-rejoin-delay: 10
    # How long should the bot wait in seconds when kicking a user? (Used to prevent whois throttles on permission checks for both users).
    # WARNING: Setting this too low could get the bot throttled. Ask your network admins what the whois throttle rate is.
    kick-delay: 1000
    # Try for an alternative nick if the main one is taken.
    auto-nick-change: true
    # Should we auto-reconnect if the bot loses connection?
    auto-reconnect: true
    # How long the bot will wait to respond to events.
    message-delay: 0
    # Should we "munge" usernames to avoid pinging users?
    munge-usernames: true
    # If a channel is in this list, the bot will completely ignore any messages in it.
    ignored-channels: []
    #- '#annoyingchannel'
    # If a user joins one of these channels, the bot will send a greeting to them. Set this to [] if you don't want any greetings.
    channels-to-greet:
    - '#Groestlcoin'


    #- '#foxbot'
    # The message to send to the user if greetings are being used.
    # Key: {USER} = The user's nick, {CHANNEL} = The channel name, {CHANUSERS} = The amount of people in the channel.
    greeting-message: '&2Welcome to &c{CHANNEL}&2, &c{USER}&2. I am GroestlBot, for more information about me type !whoami or !help into the channel. There are currently &c{CHANUSERS}&2 people in this channel, however, some of them may be away, so please be patient for a response if you have a question.&r'
    # Should we send the greeting as a notice rather than a message to the channel?
    send-greeting-as-notice: true
sounds:
    #The base URL to retrieve sound clips from for the sound command.
    sound-url: 'http://your.domain.com/sounds/'
    #The file name extension of the sounds in our remote sound database WITHOUT the "." (for example, if our sound files all ended with ".mp3" we would put mp3).
    sound-extension: 'mp3'
# List of lines that will be sent to a user when he uses the help command
help:
  - 'This is a bot ran by Jackielove4u.'
  - 'Try !whoami, !imgur, !track, !quote, !addquote, !lastquote, !findquote, !randquote, !hash, !resolve, !uptime, !ping, !wtc, !seen, or !commands for more commands.'
